# Generated by Django 3.1.3 on 2022-11-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
