# Generated by Django 3.1.3 on 2022-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
