# Generated by Django 3.1.3 on 2022-11-08 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
