# Generated by Django 3.1.3 on 2022-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
