# Generated by Django 3.1.3 on 2022-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221108_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
