# Generated by Django 3.1.3 on 2022-11-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20221108_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity',
            name='activity',
        ),
    ]
