# Generated by Django 3.1.3 on 2022-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_activity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
