# Generated by Django 3.1.3 on 2022-11-08 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20221108_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
