# Generated by Django 3.1.3 on 2022-11-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_activity',
        ),
    ]
